### ISSUE TITLE
Unexpected output when using linalg.inv with OpenBLAS backend

### ISSUE THREAD

**Issue by glynos** [rust-ndarray/ndarray-linalg#123] opened 2018-11-26 21:56 UTC
When I run the following code:

```
use ndarray::*;
use ndarray_linalg::*;

#[test]
fn inv_test() {
    let a: Array2<f64> = array!([1.0, 2.0], [3.0, 4.0]);
    let a_inv = a.inv().unwrap();
    assert!(a_inv.all_close(&array!([-2.0, 1.0], [1.5, -0.5]), 1e-5));
}
```

it produces the following output (running the command `cargo test --features=openblas`:

```
thread 'tests::inv_test' panicked at 'assertion failed: a_inv.all_close(&array!([ - 2.0 , 1.0 ] , [ 1.5 , - 0.5 ]), 1e-5)', src/main.rs:355:9
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

The value of a_inv is `vec![2, -1, -0.5, 0.5]`

I would expect the value to be the same as the example using the [equivalent using numpy](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.linalg.inv.html?highlight=inv#numpy.linalg.inv):

```
>>> from numpy.linalg import inv
>>> a = np.array([[1., 2.], [3., 4.]])
>>> ainv = inv(np.matrix(a))
>>> ainv
matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])
```

**Comment by termoshtt** [comment] 2018-11-27 07:57
Does it reproduce with other backend? e.g. intel-mkl

**Comment by glynos** [comment] 2018-11-27 18:48
The test passes when I use intel-mkl as a backend.

**Comment by termoshtt** [comment] 2018-11-27 21:14
Thanks reporting. OpenBLAS backend seems to be broken.

**Comment by stefan-k** [comment] 2019-10-13 08:45
I cannot replicate this. Maybe it was fixed in one of the dependencies?

**Comment by termoshtt** [comment] 2019-10-13 16:58
I'm closing this issue in flavor of #175. Please re-open if not fixed.

**Closed by termoshtt** 2019-10-13 16:58 UTC
Labels: bug, help wanted
